





import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author davidramirezsierra
 */


/*
 * Main.java
 *
 * Created on 20-may-2015, 19:46:05
 *
 * @author @davidramirezsierra
 *
 */


public class Main extends javax.swing.JFrame {

    static Properties mailServerProperties;
    static Session getMailSession;
    static MimeMessage generateMailMessage;

    private static String de ="";
    private static String para ="";
    private static String pass ="";
    private static String asunto ="";
    private static String texto ="";


    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo_de = new javax.swing.JTextField();
        campo_pass = new javax.swing.JPasswordField();
        campo_para = new javax.swing.JTextField();
        campo_asunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_texto = new javax.swing.JTextArea();
        boton_enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("@davidramirezsierra");

        campo_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_deActionPerformed(evt);
            }
        });

        campo_texto.setColumns(20);
        campo_texto.setRows(5);
        jScrollPane1.setViewportView(campo_texto);

        boton_enviar.setText("ENVIAR E-MAIL");
        boton_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_enviarActionPerformed(evt);
            }
        });

        jLabel1.setText("DE:");

        jLabel2.setText("PARA:");

        jLabel3.setText("ASUNTO:");

        jLabel4.setText("PASS:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel5.setText("Servicio de Correo Electrónico");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("@davidramirezsierra");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Creado por:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("para Gmail");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .add(boton_enviar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                            .add(16, 16, 16)
                                            .add(jLabel1)))
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(campo_asunto)
                                    .add(layout.createSequentialGroup()
                                        .add(campo_de, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel4)
                                        .add(32, 32, 32)
                                        .add(campo_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(campo_para, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel8)
                                .add(128, 128, 128)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel6))
                            .add(layout.createSequentialGroup()
                                .add(42, 42, 42)
                                .add(jLabel7)))
                        .add(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jLabel8))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campo_de, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(campo_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campo_para, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campo_asunto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(boton_enviar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_enviarActionPerformed

        de = campo_de.getText();
        para = campo_para.getText();
        asunto = campo_asunto.getText();
        pass = campo_pass.getText();
        texto = campo_texto.getText();
        texto = "<b>" + texto + "</b>";
        texto = texto + "<br><br><br><br>"+ "Enviado desde el programa de correo creado por @davidramirezsierra <br>";
        texto = "<P style=\"COLOR: #000000; BACKGROUND-COLOR: #E0E0E0\"> <br>"+texto.replace("\n","<br>")+"</P>";
       
        try {
                    generateAndSendEmail();
                    System.out.println("\n\n ===> Correo enviado con exito. Comprueba tu correo..");

                    campo_de.setText("");
                    campo_para.setText("");
                    campo_pass.setText("");
                    campo_asunto.setText("");
                    campo_texto.setText("MENSAJE ENVIADO CON EXITO!! Comprueba tu correo..");

                    
               } catch (AddressException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MessagingException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }


    }//GEN-LAST:event_boton_enviarActionPerformed

    private void campo_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_deActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                    new Main().setVisible(true);
                


            }
        });
    }



    public static void generateAndSendEmail() throws AddressException, MessagingException {

//Paso 1
		System.out.println("\n1 ===> Configurando las propiedades del servidor de correo..");
		mailServerProperties = System.getProperties();
		mailServerProperties.put("mail.smtp.port", "587");
		mailServerProperties.put("mail.smtp.auth", "true");
		mailServerProperties.put("mail.smtp.starttls.enable", "true");
		System.out.println("Configuracion correcta..");

//Paso 2
		System.out.println("\n\n2 ===> Estableciendo Conexión..");
		getMailSession = Session.getDefaultInstance(mailServerProperties, null);
		generateMailMessage = new MimeMessage(getMailSession);
		generateMailMessage.addRecipient(Message.RecipientType.TO, new InternetAddress(para));
		generateMailMessage.addRecipient(Message.RecipientType.CC, new InternetAddress(de));
		generateMailMessage.setSubject(asunto);
		String emailBody = texto;
		generateMailMessage.setContent(emailBody, "text/html");
		System.out.println("La sesión se ha establecido con exito..");

//Paso 3
		System.out.println("\n\n3 ===> Enviamdo mail");
		Transport transport = getMailSession.getTransport("smtp");
                
		transport.connect("smtp.gmail.com", de, pass);
                
		transport.sendMessage(generateMailMessage, generateMailMessage.getAllRecipients());
		transport.close();
	}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_enviar;
    private javax.swing.JTextField campo_asunto;
    private javax.swing.JTextField campo_de;
    private javax.swing.JTextField campo_para;
    private javax.swing.JPasswordField campo_pass;
    private javax.swing.JTextArea campo_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
